
import './globals.css'
import { Inter, Rubik } from 'next/font/google'

//components
import Navbar from './components/Navbar'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={rubik.className}>
      <Navbar></Navbar>
      <h2 className='text-center'>Test the Loading</h2>
        {children}</body>
    </html>
  )
}
